### PR TITLE
Excel workbook.

### PR DESCRIPTION
**Pull request by Entomy**
I've formatted the raw data you provided into an Excel workbook. This provides a table which makes it easier to work with and make sense of the data. Also present is some basic calculations similar to what you provided in the analysis on Survey Monkey. I intend to do some additional calculations on other pages which cross reference various datapoints for more insight. I'm providing this in hopes others might find it useful.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-foundation/wg-marketing?pullRequest=7) <br/>All CLA requirements met.

**Comment by Entomy** [comment]
I do have one thing to take care of before I take this out of draft. For the section "Which of these factors are important to you when you think about the value of .NET Foundation? (Please rank in order of importance to you.)", I'd like to put some indicator of importance beyond just the number designation. I do not remember which way this went. Would 1 or 6 be "highest importance"?

**Comment by augustoproiete** [comment]
@Entomy small typo on the file name

image

**Review by augustoproiete — CHANGES_REQUESTED** [review]
@Entomy small typo on the file name

image

**Comment by Entomy** [comment]
@augustoproiete Thanks for catching that!

**Review by BethMassi — APPROVED** [review]
Thanks for doing this!

**Comment by Entomy** [comment]
Ah, seems like this question was missed:

>For the section "Which of these factors are important to you when you think about the value of .NET Foundation? (Please rank in order of importance to you.)", I'd like to put some indicator of importance beyond just the number designation. I do not remember which way this went. Would 1 or 6 be "highest importance"?

I was holding off the merge so that I could put this information in.

**Comment by BethMassi** [comment]
Gotcha. Go ahead and submit a new PR when you're ready and I'll merge it.

**Pull request merged**
